COMMON=Node.java Edge.java MyGraph.java EdgeList.java AdjacencyList.java AdjacencyMatrix.java

DFS1.class : DFS1.java ${COMMON}
	javac -Xlint:unchecked DFS1.java ${COMMON} ${GRAPH}

DFS2.class : DFS2.java ${COMMON}
	javac -Xlint:unchecked DFS2.java ${COMMON} ${GRAPH}

BFS.class : BFS.java ${COMMON}
	javac -Xlint:unchecked BFS.java ${COMMON} ${GRAPH}
