JUNIT=/usr/share/java/junit4.jar

tree :
	javac -cp .:$(JUNIT) TestTree.java
	java -cp .:$(JUNIT) org.junit.runner.JUnitCore TestTree

traversal :
	javac -cp .:$(JUNIT) TestTraversal.java
	java -cp .:$(JUNIT) org.junit.runner.JUnitCore TestTraversal
